### ISSUE TITLE
Question about Kraken models

### ISSUE THREAD

**Issue by m7mdyahia** [OpenArabic/OCR_GS_Data#1]
Thank you about your efforts
I would like to get the configurations you used to get the results described in [this paper](https://drive.google.com/file/d/0BzDVkBcqiyEsbC16ZGktOWNiUDg/view)  from these [models](https://github.com/mittagessen/kraken-models/tree/master/clstm) 
for example
* I downloaded [al-montazem pdf](https://archive.org/download/FP76981/01_76981.pdf)
* converted it to pngs using pdftocairo without specifying resolution
* used al-montzem model for kraken

but the result I got I think is much worse than what you discribed

**Comment by m7mdyahia** [comment]
@Masoumeh @maximromanov @elijahjcooke

**Comment by maximromanov** [comment]
@m7mdyahia, regarding these questions, you need to get in touch with Ben Kiessling (mittagessen@l.unchti.me)
